#!/bin/sh
# preinst script for usdtmore.
#
# See: dh_installdeb(1).

set -e

# Summary of how this script can be called:
#        * <new-preinst> 'install'
#        * <new-preinst> 'install' <old-version>
#        * <new-preinst> 'upgrade' <old-version>
#        * <old-preinst> 'abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package.


case "$1" in
    install|upgrade)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

# 检查用户组是否已存在，如果不存在则创建
if ! getent group usdt >/dev/null; then
    addgroup --gid 975 usdt
fi

# 检查用户是否已存在，如果不存在则创建
if ! id "usdt" >/dev/null 2>&1; then
    adduser --system -uid 975 -gid 975 --no-create-home --shell /usr/sbin/nologin usdt
fi

#DEBHELPER#

exit 0
